Feature/UI 20231226
CAFECA-IO/chat-bot-lizzz pull request #2
Opened 2024-01-03 10:49 UTC by godmmt

### DEVELOP
- [ ] Homepage
- [ ] Message
- [ ] Button
- [ ] IMessage
- [ ] IChatGPTResponse
- [ ] getBotResponse

### CHECK LIST
- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 1 (axios)
- new Class / Component: 2
src/components/button.tsx
src/components/message.tsx
- new loop: 1
src/pages/index.tsx
- new recursive: 0
- high risk: 0
- new sql: 0

### UML

- [Class Diagram link](https://lucid.app/lucidchart/7f239953-18e5-41c9-94ed-648e3b3bb53d/edit?viewport_loc=-1651%2C-537%2C1923%2C1267%2C0_0&invitationId=inv_040636e5-7726-4c0c-8b2b-5230594910e8)
- [Sequence Diagram link](https://lucid.app/lucidchart/c918bc56-b89a-4d6f-8493-5037df815983/edit?viewport_loc=2172%2C1298%2C1732%2C1093%2C0_0&invitationId=inv_2ef49e7c-5f81-45de-b53e-667b661043fe)

2024-01-04 11:13 UTC, Luphia requested changes

2024-01-04 11:13 UTC, Luphia commented on package-lock.json
- remove this file

2024-01-04 11:13 UTC, Luphia commented on tailwind.config.js
- change file type to .ts

2024-01-04 11:13 UTC, Luphia commented on src/pages/index.tsx
> +const dummyMessages = [
- remove dummyMessages
- rename dummyMessages to messages with empty array

2024-01-04 11:13 UTC, Luphia commented on src/pages/index.tsx
> +                Send
- change to paper plane icon

2024-01-04 11:13 UTC, Luphia commented on src/components/message.tsx
> +    <div className={`${position}	my-1 w-fit rounded-lg bg-zinc-200	 px-2 py-1	`}>
- max-width is too wide

2024-01-10 07:33 UTC, godmmt commented on src/pages/index.tsx
> +const dummyMessages = [
updated version like this:

![截圖 2024-01-10 下午3 32 03](https://github.com/CAFECA-IO/chat-bot-lizzz/assets/105651918/aac2721a-602f-4329-909c-4ee15beacdde)

2024-01-10 11:00 UTC, Luphia approved these changes
- no bug found

2024-01-10 11:00 UTC, merged