472 update readmemd
CAFECA-IO/chat-bot-lizzz pull request #4
Opened 2024-01-12 09:41 UTC by godmmt

### DEVELOP
- [ ] 472 update readmemd

### CHECK LIST
- [Naming convention](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/technology/coding-convention/naming-convention.md) verification: checked
- Coding style verification: checked
- new Library: 0
- new Class / Component: 0
- new loop: 0
- new recursive: 0
- high risk: 0
- new sql: 0

### UML

- [Class Diagram link](https://lucid.app/lucidchart/7f239953-18e5-41c9-94ed-648e3b3bb53d/edit?viewport_loc=-1651%2C-537%2C1923%2C1267%2C0_0&invitationId=inv_040636e5-7726-4c0c-8b2b-5230594910e8)
- [Sequence Diagram link](https://lucid.app/lucidchart/c918bc56-b89a-4d6f-8493-5037df815983/edit?viewport_loc=2172%2C1298%2C1732%2C1093%2C0_0&invitationId=inv_2ef49e7c-5f81-45de-b53e-667b661043fe)

2024-01-12 09:44 UTC, godmmt commented
# 需要 Vercel 團隊權限

![截圖 2024-01-12 下午5 42 23](https://github.com/CAFECA-IO/chat-bot-lizzz/assets/105651918/ccded9e0-51c0-4c88-9da3-3bd59a4942d0)

2024-01-15 05:11 UTC, Luphia requested changes

2024-01-15 05:11 UTC, Luphia commented on src/services/chatgpt_service.ts
> +  // eslint-disable-next-line no-console
- remove console.log

2024-01-15 05:11 UTC, Luphia commented on src/pages/index.tsx
> +      role: 'assistant',
- declare static parameter

2024-01-15 05:11 UTC, Luphia commented on src/pages/index.tsx
> +      role: 'assistant',
- declare static parameter

2024-01-15 11:19 UTC, merged